name: 🐞 Issue report
description: Report a source issue
labels: [Bug]
assignees: tekuma25
body:
  - type: input
    id: source
    attributes:
      label: Source Name
      description: |
        You can find the extension name in App.
      placeholder: |
        Example: "Anplay"
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Source language
      placeholder: |
        Example: "Indonesian"
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue. Be as specific as possible.
      placeholder: |
        Example:
          1. First step (e.g. "Open Mahouka Koukou No Rettousei (first season)")
          2. Second step (e.g. "Try to watch episode 15")
          3. Issue here (e.g. "It shows a HTTP 403 error toast")
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: cs-version
    attributes:
      label: CloudStream Version
      description: |
        You can find your Cloudstream Version in Settings at Bottom.
      placeholder: |
        Example: "Red Icon  -Version" or "Blue Icon - Version"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you haven't done these steps.
      options:
        - label: I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
          required: true
        - label: I have written a short but informative title.
          required: true
        - label: I have updated the app to version **[Pre Release Updated Version](https://github.com/recloudstream/cloudstream/releases/tag/pre-release)**.
          required: true
        - label: I will fill out all of the requested information in this form.
          required: true
